# GPIO00	Led1i
# GPIO01	Led4
# GPIO02	Led3
# GPIO03	Led2
# GPIO05	Relay1
# GPIO12	Relay3
# GPIO13	Relay4
# GPIO14	Relay2
# GPIO16	Button1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: false
    id: Button1
    on_press:
      - switch.toggle: relay_usb
      - switch.toggle: relay_plug1
      - switch.toggle: relay_plug2
      - switch.toggle: relay_plug3

switch:
  - platform: gpio
    name: ${friendly_name} USB
    id: relay_usb
    pin: GPIO5
    on_turn_on:
      - output.turn_on: led_usb
    on_turn_off:
      - output.turn_off: led_usb
  - platform: gpio
    name: ${friendly_name} Plug 1
    id: relay_plug1
    pin: GPIO14
    on_turn_on:
      - output.turn_on: led_plug1
    on_turn_off:
      - output.turn_off: led_plug1
  - platform: gpio
    name: ${friendly_name} Plug 2
    id: relay_plug2
    pin: GPIO12
    on_turn_on:
      - output.turn_on: led_plug2
    on_turn_off:
      - output.turn_off: led_plug2
  - platform: gpio
    name: ${friendly_name} Plug 3
    id: relay_plug3
    pin: GPIO13
    on_turn_on:
      - output.turn_on: led_plug3
    on_turn_off:
      - output.turn_off: led_plug3


status_led:
  pin:
    number: GPIO0
    inverted: true

output:
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
    id: led_usb
  - platform: gpio
    pin: GPIO3
    id: led_plug1
  - platform: gpio
    pin: GPIO1
    id: led_plug2
  - platform: gpio
    pin: GPIO2
    id: led_plug3