binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    id: Button1
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${friendly_name}
    id: relay
    pin: GPIO14
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

status_led:
  pin:
    number: GPIO12
    inverted: true

output:
  - platform: gpio
    pin: GPIO13
    inverted: true
    id: led