# ##################################
# Gosund WB4 RGB LED Bulb
# ##################################
# GPIO12:	PWM1
# GPIO13:	PWM2
# GPIO14:	PWM3
# ##################################
# Required Substitutions
# ##################################
# device_name
# friendly_name
# ##################################

light:
  - platform: rgb
    name: ${friendly_name}
    id: rgb_light
    red: red_output
    green: green_output
    blue: blue_output
    restore_mode: ALWAYS_ON
    effects:
      !include ../rgb_effects.yaml

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO14

  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12

  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO13

interval:
  - interval: 500ms
    then:
      - if:
          condition:
            not:
              and:
                - wifi.connected:
                - api.connected:
          then:
            - light.turn_on:
                id: rgb_light
                brightness: 50%
                transition_length: 0ms
            - delay: 250ms
            - light.turn_off:
                id: rgb_light
                transition_length: 250ms