# ##################################
# Moes SS01S-1 3 Way Switch
# ##################################
# GPIO4:	Led1i (White)
# GPIO12:	Relay1
# GPIO13:	Button1
# ##################################
# Required Substitutions
# ##################################
# device_name
# friendly_name
# ##################################

status_led:
  pin:
    number: GPIO4 # White LED
    inverted: true

switch:
  - platform: gpio
    pin: GPIO12
    name: ${friendly_name}
    id: relay
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    id: button
    on_multi_click:
      !include ../button_multi_click.yaml

output:
  - platform: esp8266_pwm
    id: output_led
    pin:
      number: GPIO4
      inverted: true

light:
  - platform: monochromatic
    output: output_led
    id: led

script:
  - id: button_pushed
    then:
      - switch.toggle: relay